version: 0.0
os: linux
files:
  - source: /
    destination: /app
hooks:
  ApplicationStart:
    - location: ./deploy.sh
      runas: root
      timeout: 120
      env:
        - name: IMAGE_TAG
          value: '#{Build.IMAGE_TAG}'
