version: 0.2
env:
  variables:
    PROJECT_VERSION: 1.0.0
  parameter-store:
    DOCKER_HUB_USER: /libz/dockerhub/user
    DOCKER_HUB_TOKEN: /libz/dockerhub/token
    ECR_ENDPOINT: /libz/ecr/endpoint
    RSI_CLIENT_ID: /libz/app/rsi/client-id
    RSI_AUTH_REDIRECT_URL: /libz/app/rsi/auth-redirect-url

phases:
  pre_build:
    on-failure: ABORT
    commands:
      - export VERSION_TAG=${PROJECT_VERSION}-$(echo ${CODEBUILD_RESOLVED_SOURCE_VERSION} | cut -c 1-7)
      - export IMAGE_TAG=${ECR_ENDPOINT}/libz:${VERSION_TAG}
      - aws ecr get-login-password |
          docker login --username AWS --password-stdin ${ECR_ENDPOINT}
      - echo ${DOCKER_HUB_TOKEN} |
          docker login -u ${DOCKER_HUB_USER} --password-stdin
  build:
    on-failure: ABORT
    commands:
      - docker build .
          -t ${IMAGE_TAG}
          --build-arg RSI_CLIENT_ID=${RSI_CLIENT_ID}
          --build-arg RSI_AUTH_REDIRECT_URL=${RSI_AUTH_REDIRECT_URL}
  post_build:
    on-failure: ABORT
    commands:
      - docker push ${IMAGE_TAG}
      - printf '{ "imageTag":"%s" }' ${IMAGE_TAG} > artifacts.json
artifacts:
  files:
    - appspec.yml
    - artifacts.json
    - tools/deploy.sh
  discard-paths: yes
