version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: libz-backend
    container_name: libz-backend
    ports:
      - 3304:3304
    volumes:
      - ./backend:/backend
    networks:
      - libz-network
    working_dir: /backend
    environment:
      TZ: Asia/Tokyo
      DATABASE_HOST: database
      DATABASE_PORT: 3306
      DATABASE_USER: master
      DATABASE_PASSWORD: password
      DATABASE_NAME: libz
    tty: true
    restart: on-failure
    command: uvicorn src.main:app --host 0.0.0.0 --port 3304 --reload
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - RSI_CLIENT_ID=xxxxxxxx
        - RSI_AUTH_REDIRECT_URL=https://www.example.com/login/redirect
    image: libz-frontend
    container_name: libz-frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
      - frontend-node-modules:/frontend/node_modules
      - frontend-dist:/frontend/dist
    networks:
      - libz-network
    working_dir: /frontend
    environment:
      TZ: Asia/Tokyo
    tty: true
    restart: on-failure
  
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: libz-server
    container_name: libz-server
    ports:
      - 8000:80
    volumes:
      - ./server/nginx.conf:/etc/nginx/nginx.conf
      - ./server/development.d:/etc/nginx/conf.d
      - ./server/log:/var/log/nginx
      - frontend-dist:/frontend/dist
    networks:
      - libz-network
    environment:
      TZ: Asia/Tokyo
    tty: true
    restart: on-failure
  
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: libz-database
    container_name: libz-database
    ports:
      - 3306:3306
    volumes:
      - database-volume:/var/lib/mysql
      - ./database/conf/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - libz-network
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: master
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: libz
    tty: true
    restart: on-failure

  schemaspy:
    build:
      context: ./database
      dockerfile: schemaspy/Dockerfile
    image: libz-schemaspy
    container_name: libz-schemaspy
    depends_on:
      - database
    volumes:
      - ./database/schemaspy/output:/output
      - ./database/schemaspy/schemaspy.properties:/schemaspy.properties
    networks:
      - libz-network
    environment:
      TZ: Asia/Tokyo
    tty: true
    restart: on-failure

volumes:
  frontend-node-modules:
  frontend-dist:
  database-volume:

networks:
  libz-network:
