CODE_USER_INACTIVE = '4000'
MESSAGE_USER_INACTIVE = "User authentication failure."

CODE_USER_NOT_FOUND = '4040'
MESSAGE_USER_NOT_FOUND = "Invalid user."

CODE_TENANT_NOT_FOUND = '4041'
MESSAGE_TENANT_NOT_FOUND = "Invalid user."

CODE_KNOWLEDGE_NOT_FOUND = '1040'
MESSAGE_KNOWLEDGE_NOT_FOUND = "Knowledge not found."

CODE_UNKNOWN = '9999'
MESSAGE_UNKNOWN = "Unknown error."
