Resources:
  KeyPair:
    Type: AWS::EC2::KeyPair
    DeletionPolicy: Retain
    Properties:
      KeyName: libz-keypair

Outputs:
  OutputKeyPair:
    Value: !Ref KeyPair
    Export:
      Name: libz-keypair
