Parameters:
  DBUser:
    Type: AWS::SSM::Parameter::Name
    Default: /libz/db/user
    Description: DB username.
    AllowedValues:
      - /libz/db/user
  DBPassword:
    Type: AWS::SSM::Parameter::Name
    Default: /libz/db/password
    Description: DB password.
    AllowedValues:
      - /libz/db/password
  InstanceClass:
    Type: String
    Default: db.t3.micro
    Description: DB instance class
    AllowedValues:
      - db.t3.micro
      - db.t3.small
      - db.m5d.large
  StorageSize:
    Type: Number
    Default: 20
    Description: Storage size [GB]
    MinValue: 20
    MaxValue: 2048

Resources:
  DBSubnets:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: libz-db-subnets
      DBSubnetGroupDescription: libz-db-subnets
      SubnetIds:
          - !ImportValue libz-private-subnet-1a
          - !ImportValue libz-private-subnet-1c

  DBPG:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: libz-db-pg
      Family: mariadb10.11
      Parameters:
        character_set_client: utf8mb4
        character_set_connection: utf8mb4
        character_set_database: utf8mb4
        character_set_results: utf8mb4
        character_set_server: utf8mb4
        collation_connection: utf8mb4_general_ci
        collation_server: utf8mb4_general_ci

  DB:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete
    Properties:
      Engine: mariadb
      EngineVersion: 10.11
      AllowMajorVersionUpgrade: true
      AutoMinorVersionUpgrade: true
      DBInstanceIdentifier: libz-db
      DBInstanceClass: !Ref InstanceClass
      PubliclyAccessible: false
      MultiAZ: false
      DBSubnetGroupName: !Ref DBSubnets
      DBParameterGroupName: !Ref DBPG
      VPCSecurityGroups:
        - !ImportValue libz-db-sg
      StorageType: gp2
      AllocatedStorage: !Ref StorageSize
      MaxAllocatedStorage: !Ref StorageSize
      StorageEncrypted: true
      CACertificateIdentifier: rds-ca-rsa4096-g1
      BackupRetentionPeriod: 14
      MasterUsername: !Sub '{{resolve:ssm:${DBUser}}}'
      MasterUserPassword: !Sub '{{resolve:ssm-secure:${DBPassword}}}'
      DBName: libz
      DeletionProtection: false
      CopyTagsToSnapshot: true
      MonitoringInterval: 60
      MonitoringRoleArn: !ImportValue libz-db-monitoring-role
      EnableCloudwatchLogsExports:
        - audit
        - error
        - general
        - slowquery
