Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: 'libz-search.net'
      ValidationMethod: DNS
      KeyAlgorithm: RSA_2048
  
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: application
      Name: libz-alb
      Subnets:
        - !ImportValue libz-public-subnet-1a
        - !ImportValue libz-public-subnet-1c
        - !ImportValue libz-public-subnet-1d
      SecurityGroups:
        - !ImportValue libz-alb-sg
      LoadBalancerAttributes:
        - Key: deletion_protection.enabled
          Value: true
        - Key: routing.http.drop_invalid_header_fields.enabled
          Value: true
        - Key: access_logs.s3.enabled
          Value: true
        - Key: access_logs.s3.bucket
          Value: !ImportValue libz-bucket
        - Key: access_logs.s3.prefix
          Value: access
        - Key: connection_logs.s3.enabled
          Value: true
        - Key: connection_logs.s3.bucket
          Value: !ImportValue libz-bucket
        - Key: connection_logs.s3.prefix
          Value: connection

  ECSTG:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: libz-ecs-tg
      Protocol: HTTP
      Port: 80
      VpcId: !ImportValue libz-vpc

  ECSTG2:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: libz-ecs-tg-green
      Protocol: HTTP
      Port: 8080
      VpcId: !ImportValue libz-vpc

  AppListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALB
      Protocol: HTTP
      Port: 80
      DefaultActions:
        - Type: redirect
          RedirectConfig:
            Protocol: HTTPS
            Host: '#{host}'
            Port: 443
            Path: '/#{path}'
            Query: '#{query}'
            StatusCode: HTTP_301

  AppListenerSSL:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALB
      Protocol: HTTPS
      Port: 443
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ECSTG
      Certificates:
        - CertificateArn: !Ref Certificate

  TestListenerSSL:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALB
      Protocol: HTTPS
      Port: 8443
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ECSTG
      Certificates:
        - CertificateArn: !Ref Certificate

Outputs:
  OutputALBDNS:
    Value: !GetAtt ALB.DNSName
    Export:
      Name: libz-alb-dns
  OutputALBHZ:
    Value: !GetAtt ALB.CanonicalHostedZoneID
    Export:
      Name: libz-alb-hz
  OutputECSTG:
    Value: !Ref ECSTG
    Export:
      Name: libz-ecs-tg
  OutputECSTG2:
    Value: !Ref ECSTG2
    Export:
      Name: libz-ecs-tg-green
  OutputAppListenerSSL:
    Value: !Ref AppListenerSSL
    Export:
      Name: libz-app-listener
  OutputTestListenerSSL:
    Value: !Ref TestListenerSSL
    Export:
      Name: libz-test-listener
