Parameters:
  Env:
    Type: String
    Default: dev
    Description: Env
    AllowedValues:
      - dev
      - production

Resources:
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: application
      Name: libz-alb
      Subnets:
        - !ImportValue libz-public-subnet-1a
        - !ImportValue libz-public-subnet-1c
        - !ImportValue libz-public-subnet-1d
      SecurityGroups:
        - !ImportValue libz-alb-sg
      LoadBalancerAttributes:
        - Key: deletion_protection.enabled
          Value: true
        - Key: routing.http.drop_invalid_header_fields.enabled
          Value: true

  AppTG:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub libz-app-tg
      Protocol: HTTP
      Port: 80
      Targets:
        - Id:
            Fn::ImportValue: !Sub libz-${Env}-app-instance
      VpcId: !ImportValue libz-vpc

  AppListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALB
      Protocol: HTTP
      Port: 80
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref AppTG

Outputs:
  OutputAppTG:
    Value: !Ref AppTG
    Export:
      Name: libz-app-tg
